CREATE DATABASE gerenciador_tarefaz;

USE gerenciador_tarefaz;

CREATE TABLE tarefa(
 id INT AUTO_INCREMENT PRIMARY KEY,
 titulo VARCHAR(100)NOT NULL,
 descricao VARCHAR(200)NOT NULL,
 status VARCHAR(20) NOT NULL DEFAULT'pendente',
 data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);